# パッケージ追加時、requirements.in -> requirements.txt への反映に使用
# $ docker-compose -f docker-compose.piptools.yml run --rm piptools

services:
  piptools:
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install pip-tools && pip-compile requirements.in"
