[tool.ruff]
line-length = 88        # 任意で変更
target-version = "py38" # あなたのPythonバージョンに合わせて
fix = true              # 自動修正を有効化

[tool.ruff.format]
quote-style = "double" # black風にしたいなら
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A002",
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ARG001",
    "B006",
    "B008",
    "B015",
    "B017",
    "BLE001",
    "C901",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "D200",
    "D400",
    "D415",
    "DTZ001",
    "DTZ005",
    "E402",
    "E501",
    "E722",
    "EM101",
    "EM102",
    "ERA001",
    "EXE001",
    "FA100",
    "FBT001",
    "FBT002",
    "INP001",
    "ISC003",
    "N999",
    "PERF401",
    "PGH004",
    "PLC0206",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PT011",
    "PT012",
    "PTH100",
    "PTH120",
    "PTH123",
    "RET503",
    "RSE102",
    "RUF001",
    "RUF003",
    "RUF013",
    "S101",
    "S104",
    "S105",
    "S106",
    "S311",
    "SIM115",
    "SLF001",
    "T100",
    "T201",
    "TC001",
    "TC003",
    "TRY002",
    "TRY003",
    "TRY004",
    "TRY300",
]
