from .user.FollowUseCase import FollowUseCase
from .user.GetUsersForWebUseCase import GetUsersForWebUseCase
from .user.UnfollowUseCase import UnfollowUseCase

from .group.JoinRoomUseCase import JoinRoomUseCase

from .AddPointByTextUseCase import AddPointByTextUseCase
from .StartInputUseCase import StartInputUseCase
from .RoomQuitUseCase import RoomQuitUseCase
from .MatchFinishUseCase import MatchFinishUseCase
from .ReplyRoomModeUseCase import ReplyRoomModeUseCase
from .ReplyUserModeUseCase import ReplyUserModeUseCase
from .ChangeUserModeUseCase import ChangeUserModeUseCase
from .ReplyFortuneUseCase import ReplyFortuneUseCase
from .ReplyUserHelpUseCase import ReplyUserHelpUseCase
from .ReplyRoomHelpUseCase import ReplyRoomHelpUseCase
from .ReplySumHanchansUseCase import ReplySumHanchansUseCase
from .ReplySumHanchansByMatchIdUseCase import ReplySumHanchansByMatchIdUseCase
from .ReplyMatchesUseCase import ReplyMatchesUseCase
from .ReplyGitHubUrlUseCase import ReplyGitHubUrlUseCase
from .SetMyZoomUrlToRoomUseCase import SetMyZoomUrlToRoomUseCase
from .hanchan.AddHanchanByPointsTextUseCase import AddHanchanByPointsTextUseCase
from .SetZoomUrlToUserUseCase import SetZoomUrlToUserUseCase
from .SetZoomUrlToRoomUseCase import SetZoomUrlToRoomUseCase
from .CalculateWithTobiUseCase import CalculateWithTobiUseCase
from .GetConfigsForWebUseCase import GetConfigsForWebUseCase
from .GetHanchansForWebUseCase import GetHanchansForWebUseCase
from .GetMatchesForWebUseCase import GetMatchesForWebUseCase
from .GetRoomsForWebUseCase import GetRoomsForWebUseCase
from .ReplyRoomSettingsMenuUseCase import ReplyRoomSettingsMenuUseCase
from .ReplyStartMenuUseCase import ReplyStartMenuUseCase
from .ReplyOthersMenuUseCase import ReplyOthersMenuUseCase
from .AddPointByJsonTextUseCase import AddPointByJsonTextUseCase
from .UpdateConfigUseCase import UpdateConfigUseCase
from .InputResultFromImageUseCase import InputResultFromImageUseCase
from .ReplySumMatchesByIdsUseCase import ReplySumMatchesByIdsUseCase
from .ReplyRoomZoomUrlUseCase import ReplyRoomZoomUrlUseCase
from .DropHanchanByIndexUseCase import DropHanchanByIndexUseCase
from .DisableMatchUseCase import DisableMatchUseCase

follow_use_case = FollowUseCase()
unfollow_use_case = UnfollowUseCase()
join_room_use_case = JoinRoomUseCase()
add_hanchan_by_points_text_use_case = AddHanchanByPointsTextUseCase()
add_point_by_text_use_case = AddPointByTextUseCase()
add_point_by_Json_text_use_case = AddPointByJsonTextUseCase()
drop_hanchan_by_index_use_case = DropHanchanByIndexUseCase()
start_input_use_case = StartInputUseCase()
room_quit_use_case = RoomQuitUseCase()
match_finish_use_case = MatchFinishUseCase()
reply_user_mode_use_case = ReplyUserModeUseCase()
reply_room_mode_use_case = ReplyRoomModeUseCase()
change_user_mode_use_case = ChangeUserModeUseCase()
reply_fortune_use_case = ReplyFortuneUseCase()
reply_sum_hanchans_use_case = ReplySumHanchansUseCase()
reply_sum_hanchans__by_match_id_use_case = ReplySumHanchansByMatchIdUseCase()
reply_matches_use_case = ReplyMatchesUseCase()
reply_user_help_use_case = ReplyUserHelpUseCase()
reply_room_help_use_case = ReplyRoomHelpUseCase()
reply_github_url_use_case = ReplyGitHubUrlUseCase()
reply_start_menu_use_case = ReplyStartMenuUseCase()
reply_others_menu_use_case = ReplyOthersMenuUseCase()
reply_room_settings_menu_use_case = ReplyRoomSettingsMenuUseCase()
reply_room_zoom_url_use_case = ReplyRoomZoomUrlUseCase()
set_my_zoom_url_to_room_use_case = SetMyZoomUrlToRoomUseCase()
set_zoom_url_to_user_use_case = SetZoomUrlToUserUseCase()
set_zoom_url_to_room_use_case = SetZoomUrlToRoomUseCase()
calculate_with_tobi_use_case = CalculateWithTobiUseCase()
get_rooms_for_web_use_case = GetRoomsForWebUseCase()
get_configs_for_web_use_case = GetConfigsForWebUseCase()
get_hanchans_for_web_use_case = GetHanchansForWebUseCase()
get_matches_for_web_use_case = GetMatchesForWebUseCase()
get_users_for_web_use_case = GetUsersForWebUseCase()
update_config_use_case = UpdateConfigUseCase()
input_result_from_image_use_case = InputResultFromImageUseCase()
reply_sum_matches_by_ids_use_case = ReplySumMatchesByIdsUseCase()
disable_match_use_case = DisableMatchUseCase()
